### ISSUE TITLE
Little bit of refactoring

### ISSUE THREAD

**Issue by tomirons** [tomirons/laravel-accountant-old#10]
The majority of the grunt work for creating the classes and getting them to work has been done, now I'd like your help to make them better. 😄 Here's a list of classes I'd like to focus on first, then we can venture into the other parts.

- Cabinet : https://github.com/tomirons/laravel-accountant/blob/master/src/Cabinet.php
- Client : https://github.com/tomirons/laravel-accountant/blob/master/src/Client.php
- Paginator : https://github.com/tomirons/laravel-accountant/blob/master/src/Paginator.php

**Comment by JafarAkhondali** [comment]
What exactly do you mean by "Little bit of refactoring" ? What thing do you expect?

**Comment by tomirons** [comment]
I believe there's a way to clean them up a bit and make them more "readable".
